#!/usr/bin/env python3
"""
Limpieza final: Elimina etiquetas de Tipo y asegura que todo esté en inglés
"""
import re
from pathlib import Path


def remove_type_labels(content: str) -> str:
    """Elimina las líneas que dicen **Tipo:** 🔤 Texto o **Tipo:** 🎨 Visual"""
    pattern = r'\*\*Tipo:\*\* [🔤🎨].*?\n\n'
    content = re.sub(pattern, '', content)
    return content


def ensure_english_headers(content: str) -> str:
    """Asegura que los headers estén en inglés"""
    translations = {
        'Tabla de Contenidos': 'Table of Contents',
        'Contenido': 'Content',
        'Análisis Visual': 'Visual Analysis',
        'Metadatos de Procesamiento': 'Processing Metadata',
        'Clasificación de Slides': 'Slide Classification',
        'Costos de API': 'API Costs',
        'Sistema': 'System',
        'Slides de texto': 'Text slides',
        'Slides visuales': 'Visual slides',
        'Porcentaje optimizado (sin API)': 'Optimized percentage (without API)',
        'Tokens de entrada': 'Input tokens',
        'Tokens de salida': 'Output tokens',
        'Costo total': 'Total cost',
        'Generado por': 'Generated by',
        'Fecha de conversión': 'Conversion date',
        'Archivo original': 'Original file',
        'Total de slides': 'Total slides',
        'Fecha': 'Date'
    }

    for spanish, english in translations.items():
        content = content.replace(spanish, english)

    return content


def cleanup_file(md_path: Path) -> bool:
    """Limpia un archivo markdown"""
    print(f"Processing: {md_path.name}...", end='')

    try:
        content = md_path.read_text(encoding='utf-8')

        # Aplicar limpiezas
        content = remove_type_labels(content)
        content = ensure_english_headers(content)

        md_path.write_text(content, encoding='utf-8')
        print(" ✓")
        return True
    except Exception as e:
        print(f" ✗ Error: {e}")
        return False


def main():
    md_dir = Path(__file__).parent / 'markdown'
    md_files = sorted(md_dir.glob('*.md'))

    print(f"\n🧹 Final cleanup of {len(md_files)} markdown files\n")

    success_count = 0
    for md_file in md_files:
        if cleanup_file(md_file):
            success_count += 1

    print(f"\n✓ Completed: {success_count}/{len(md_files)} files processed")


if __name__ == '__main__':
    main()
